/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ArcHireEscrow {
  export type JobStruct = {
    buyer: AddressLike;
    agent: AddressLike;
    amount: BigNumberish;
    status: BigNumberish;
    deliveryHash: string;
  };

  export type JobStructOutput = [
    buyer: string,
    agent: string,
    amount: bigint,
    status: bigint,
    deliveryHash: string
  ] & {
    buyer: string;
    agent: string;
    amount: bigint;
    status: bigint;
    deliveryHash: string;
  };
}

export interface ArcHireEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveAndRelease"
      | "authorizedAgents"
      | "createJob"
      | "dispute"
      | "getJob"
      | "jobs"
      | "nextJobId"
      | "owner"
      | "refund"
      | "renounceOwnership"
      | "setAgentAddress"
      | "submitDelivery"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentAuthorizationUpdated"
      | "JobCreated"
      | "JobDelivered"
      | "JobDisputed"
      | "JobRefunded"
      | "JobReleased"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveAndRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "nextJobId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentAddress",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDelivery",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "approveAndRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dispute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextJobId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace AgentAuthorizationUpdatedEvent {
  export type InputTuple = [agent: AddressLike, authorized: boolean];
  export type OutputTuple = [agent: string, authorized: boolean];
  export interface OutputObject {
    agent: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    buyer: AddressLike,
    agent: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    buyer: string,
    agent: string,
    amount: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    buyer: string;
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobDeliveredEvent {
  export type InputTuple = [jobId: BigNumberish, deliveryHash: string];
  export type OutputTuple = [jobId: bigint, deliveryHash: string];
  export interface OutputObject {
    jobId: bigint;
    deliveryHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobDisputedEvent {
  export type InputTuple = [jobId: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [jobId: bigint, buyer: string];
  export interface OutputObject {
    jobId: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobRefundedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobReleasedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    agent: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, agent: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcHireEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ArcHireEscrow;
  waitForDeployment(): Promise<this>;

  interface: ArcHireEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveAndRelease: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizedAgents: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  createJob: TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  dispute: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [ArcHireEscrow.JobStructOutput],
    "view"
  >;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string] & {
        buyer: string;
        agent: string;
        amount: bigint;
        status: bigint;
        deliveryHash: string;
      }
    ],
    "view"
  >;

  nextJobId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAgentAddress: TypedContractMethod<
    [agent: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  submitDelivery: TypedContractMethod<
    [jobId: BigNumberish, deliveryHash: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveAndRelease"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedAgents"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dispute"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [ArcHireEscrow.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string] & {
        buyer: string;
        agent: string;
        amount: bigint;
        status: bigint;
        deliveryHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextJobId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentAddress"
  ): TypedContractMethod<
    [agent: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitDelivery"
  ): TypedContractMethod<
    [jobId: BigNumberish, deliveryHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgentAuthorizationUpdated"
  ): TypedContractEvent<
    AgentAuthorizationUpdatedEvent.InputTuple,
    AgentAuthorizationUpdatedEvent.OutputTuple,
    AgentAuthorizationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobDelivered"
  ): TypedContractEvent<
    JobDeliveredEvent.InputTuple,
    JobDeliveredEvent.OutputTuple,
    JobDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "JobDisputed"
  ): TypedContractEvent<
    JobDisputedEvent.InputTuple,
    JobDisputedEvent.OutputTuple,
    JobDisputedEvent.OutputObject
  >;
  getEvent(
    key: "JobRefunded"
  ): TypedContractEvent<
    JobRefundedEvent.InputTuple,
    JobRefundedEvent.OutputTuple,
    JobRefundedEvent.OutputObject
  >;
  getEvent(
    key: "JobReleased"
  ): TypedContractEvent<
    JobReleasedEvent.InputTuple,
    JobReleasedEvent.OutputTuple,
    JobReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AgentAuthorizationUpdated(address,bool)": TypedContractEvent<
      AgentAuthorizationUpdatedEvent.InputTuple,
      AgentAuthorizationUpdatedEvent.OutputTuple,
      AgentAuthorizationUpdatedEvent.OutputObject
    >;
    AgentAuthorizationUpdated: TypedContractEvent<
      AgentAuthorizationUpdatedEvent.InputTuple,
      AgentAuthorizationUpdatedEvent.OutputTuple,
      AgentAuthorizationUpdatedEvent.OutputObject
    >;

    "JobCreated(uint256,address,address,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobDelivered(uint256,string)": TypedContractEvent<
      JobDeliveredEvent.InputTuple,
      JobDeliveredEvent.OutputTuple,
      JobDeliveredEvent.OutputObject
    >;
    JobDelivered: TypedContractEvent<
      JobDeliveredEvent.InputTuple,
      JobDeliveredEvent.OutputTuple,
      JobDeliveredEvent.OutputObject
    >;

    "JobDisputed(uint256,address)": TypedContractEvent<
      JobDisputedEvent.InputTuple,
      JobDisputedEvent.OutputTuple,
      JobDisputedEvent.OutputObject
    >;
    JobDisputed: TypedContractEvent<
      JobDisputedEvent.InputTuple,
      JobDisputedEvent.OutputTuple,
      JobDisputedEvent.OutputObject
    >;

    "JobRefunded(uint256,address,uint256)": TypedContractEvent<
      JobRefundedEvent.InputTuple,
      JobRefundedEvent.OutputTuple,
      JobRefundedEvent.OutputObject
    >;
    JobRefunded: TypedContractEvent<
      JobRefundedEvent.InputTuple,
      JobRefundedEvent.OutputTuple,
      JobRefundedEvent.OutputObject
    >;

    "JobReleased(uint256,address,uint256)": TypedContractEvent<
      JobReleasedEvent.InputTuple,
      JobReleasedEvent.OutputTuple,
      JobReleasedEvent.OutputObject
    >;
    JobReleased: TypedContractEvent<
      JobReleasedEvent.InputTuple,
      JobReleasedEvent.OutputTuple,
      JobReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
